services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tasker
      POSTGRES_PASSWORD: tasker
      POSTGRES_DB: tasker
    ports:
      - "5432:5432"
    volumes:
      - tasker_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasker -d tasker"]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 10s

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  tasker_pg:
